name: Linux-Bash
on:
  workflow_dispatch:
  pull_request:

env:
  env_key: "env_value"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line bash script
        run: |
          echo "Global variable:" $env:env_key
          echo "Local variable:" $env:GH_VAR
          echo "Host variable:" $env:APPDATA
          echo "GitHub variable:" $env:GITHUB_SHA
          echo "Secret:" ${{ secrets.SECRET_KEY }}
          echo "Local Secret:" $env:GH_SECRET
        env: 
          GH_SECRET: ${{ secrets.SECRET_KEY }}
          GH_VAR: ${{ env.env_key }}

      - name: Run shell script
        run: ./scripts/bash/echo.sh
        shell: bash
        env: 
          GA_SECRET: ${{ secrets.SECRET_KEY }}
          GA_VAR: ${{ env.env_key }}