name: Linux-Bash
on:
  workflow_dispatch:
  pull_request:

env:
  env_key: "env_value"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line bash script
        run: |
          echo "Hello"
          echo "World"

      - name: Run shell script
        run: ./scripts/bash/echo.sh
        shell: bash
        # env: 
        #   GA_SECRET: ${{ secrets.SECRET_KEY }}
        #   GA_VAR: ${{ env.env_key }}