name: Windows-PowerShell
on:
  workflow_dispatch:

env:
  env_key: "env_value"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line ps1 script
        shell: pwsh
        run: |
          $x = ${{ secrets.SECRET_KEY }}
          Write-Host Hello $x
          Write-Host Appdata $env:APPDATA
        
      - name: Run shell script
        run: ./scripts/ps/echo.ps1

        env: 
          GA_SECRET: ${{ secrets.SECRET_KEY }}
          GA_VAR: ${{ env.env_key }}