name: Windows-PowerShell
on:
  workflow_dispatch:
  pull_request:

env:
  env_key: "env_value"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line ps1 script
        shell: pwsh
        run: |
          Write-Host Global variable: $env:env_key
          Write-Host Local variable: $env:GH_VAR
          Write-Host Host variable: $env:APPDATA
          Write-Host GitHub variable: $env:GITHUB_SHA
          Write-Host Secret: ${{ secrets.SECRET_KEY }}
          Write-Host Local Secret: $env:GH_SECRET
        env: 
          GH_SECRET: ${{ secrets.SECRET_KEY }}
          GH_VAR: ${{ env.env_key }}
        
      - name: Run ps1 script
        run: ./scripts/ps/echo.ps1
        env: 
          GH_SECRET: ${{ secrets.SECRET_KEY }}
          GH_VAR: ${{ env.env_key }}